/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell 7404
 */
public class hotelservice extends javax.swing.JFrame {

    /**
     * Creates new form hotelService
     */
    public hotelservice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress1 = new javax.swing.JTextField();
        jtxtPostcode = new javax.swing.JTextField();
        jtxtTellno = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jtxtNationality = new javax.swing.JTextField();
        jtxtDateofbirth = new javax.swing.JTextField();
        jtxtCheckindate = new javax.swing.JTextField();
        jtxtCheckoutdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();
        jbtnreset = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jbtntotal = new javax.swing.JButton();
        jcomboIdtype = new javax.swing.JComboBox<>();
        jcomboGender = new javax.swing.JComboBox<>();
        jcomboRoomtype = new javax.swing.JComboBox<>();
        jcomboRoomno = new javax.swing.JComboBox<>();
        jtxtCustomerref = new javax.swing.JTextField();
        jcomboMeal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("SUMMIIT HOTEL");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 400, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Meal");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleName("Post code");

        jtxtEmail.setToolTipText("Email");
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 30));

        jtxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, 30));

        jtxtSurname.setName(""); // NOI18N
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));
        getContentPane().add(jtxtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 30));

        jtxtPostcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostcodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, 30));
        getContentPane().add(jtxtTellno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, 30));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("Surname:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setText("First Name:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setText("Email:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("Customers ref:");
        jLabel29.setToolTipText("");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setText("Address 1:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setText("Postcode:");
        jLabel31.setToolTipText("postcode");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setText("Tell no:");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setText("Nationality");
        jLabel37.setToolTipText("");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        jLabel58.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel58.setText("Id type");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel59.setText("Date of birth");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel60.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel60.setText("Room no:");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 100, -1));

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel62.setText("Gender");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel63.setText("Check out date:");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel64.setText("Check in date");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel65.setText("Room type");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        getContentPane().add(jtxtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 30));
        getContentPane().add(jtxtDateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 160, 30));
        getContentPane().add(jtxtCheckindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 160, 30));
        getContentPane().add(jtxtCheckoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ref", "First Name", "Surname", "Address 1", "Meal", "Tell No", "Email", "Nationality", "Date of birth", "ID type", "Gender", "Check in date", "Check out date", "Room type", "Room no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1310, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel34.setText("Tax:");

        jLabel35.setText("Sub total:");

        jLabel36.setText("Total:");

        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubtotalActionPerformed(evt);
            }
        });

        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jbtnexit.setText("Exit");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });

        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jbtntotal.setText("Total");
        jbtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jtxtSubtotal))
                        .addGap(54, 54, 54)
                        .addComponent(jbtntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(886, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 1590, 130));

        jcomboIdtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student ID", "Driving license", "Passport", "Plot license" }));
        jcomboIdtype.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcomboIdtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboIdtypeActionPerformed(evt);
            }
        });
        getContentPane().add(jcomboIdtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 160, 30));

        jcomboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jcomboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jcomboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 160, 30));

        jcomboRoomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Family", "Doble" }));
        getContentPane().add(jcomboRoomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 160, -1));

        jcomboRoomno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014" }));
        getContentPane().add(jcomboRoomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 160, 30));

        jtxtCustomerref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerrefActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCustomerref, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 30));

        jcomboMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chips", "sausage", "beef", "stew", "pork", "rice", "plain beans", "chapo" }));
        getContentPane().add(jcomboMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstNameActionPerformed

    private void jtxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubtotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    //the exit button codes;
    private JFrame frame;
    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
         frame = new JFrame();
      if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hotel Management System",
              JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
          System.exit(0);       
      }
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntotalActionPerformed
        //rooms
        int Single =34;
        int Doble = 15;
        int Family=78;
        //meal
         
        int chips =7;
        int beef = 11;
        int chapo=3;
        int rice =4;
        int plainbeans = 5;
        int sausage=8;
         int pork =6;
        int stew= 1;
        
        SimpleDateFormat format= new SimpleDateFormat("yyyy-mm-dd");
        Date Check_In_Date=null;
            Date Check_Out_Date=null;
            
            try{
            Check_In_Date=format.parse(format.format(jtxtCheckindate.getDate()));
             Check_Out_Date=format.parse(format.format(jtxtCheckoutdate.getDate()));
            }
            catch(Exception e)
            {
            e.printStackTrace();
            }
            
            long Checkdiff= Check_In_Date.getTime()- Check_Out_Date.getTime();
            int Daysdiff=(int)(Checkdiff /1000/60/60/24);
            
            
        
        if(jcomboRoomtype.getSelectedItem().equals("Single") && jcomboMeal.getSelectedItem().equals("chips"))
        {
        jtxtTotal.setText(Integer.toString(Daysdiff*Single)+chips);
         jtxtTax.setText(Integer.toString(Daysdiff*Single)+chips);
          jtxtSubtotal.setText(Integer.toString(Daysdiff*Single)+chips);
         
          double q = Double.parseDouble(jtxtTax.getText());
          q=(q*0.25)/100;
          String tax=String.format(($ %.2f),q);
          jtxtTax.setText(tax);
          
          double st = Double.parseDouble(jtxtSubtotal.getText());
          String Subtotal=String.format(($ %.2f),st);
          jtxtSubtotal.setText(Subtotal);
          
             double tt = Double.parseDouble(jtxtTotal.getText());
          String Total=String.format(($ %.2f),tt+q);
          jtxtTotal.setText(Total);
          
          
        }
            
            
            
        //====================================================================
        DefaultTableModel  model = (DefaultTableModel)  jTable1.getModel();
        model.addRow(new Object[]{
        
        jtxtCustomerref.getText(),
             jtxtFirstName.getText(),
              jtxtSurname.getText(),
               jtxtAddress1.getText(),
                jcomboMeal.getSelectedItem(),
                 jtxtTellno.getText(),
                  jtxtEmail.getText(),
                   jtxtNationality.getText(),
                   jtxtDateofbirth.getText(),
                      jcomboIdtype.getSelectedItem(),
                      jcomboGender.getSelectedItem(),
                          jtxtCheckindate.getText(),
                       jtxtCheckoutdate.getText(),
                        jcomboRoomtype.getSelectedItem(),
               jcomboRoomno.getSelectedItem()
                        
                   
        });
        
        
    }//GEN-LAST:event_jbtntotalActionPerformed

    
    // delete btn code
    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
      DefaultTableModel  model = (DefaultTableModel)  jTable1.getModel();
      if (jTable1.getSelectedRow() == -1) {
      if(jTable1.getRowCount() == 0){
          JOptionPane.showMessageDialog(null, "No data to delete","Hotel Management System",JOptionPane.OK_CANCEL_OPTION);
     
      }else{
       JOptionPane.showMessageDialog(null, "Select a row to delete","Hotel Management System",JOptionPane.OK_CANCEL_OPTION);
      }
      }else{
      model.removeRow(jTable1.getSelectedRow());
      }
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jcomboIdtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboIdtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboIdtypeActionPerformed

    private void jcomboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboGenderActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        DefaultTableModel  model = (DefaultTableModel)  jTable1.getModel();
        model.setRowCount(0);
        
        jtxtCustomerref.setText(null);
        jtxtFirstName.setText(null);
        jtxtSurname.setText(null);
         jtxtAddress1.setText(null);
         jtxtPostcode.setText(null);
        jcomboMeal.setSelectedIndex(0);
        jtxtTellno.setText(null);
        jtxtEmail.setText(null);
        jtxtNationality.setText(null);
        jtxtDateofbirth.setText(null);
        jcomboIdtype.setSelectedIndex(0);
         jcomboGender.setSelectedIndex(0);
        jtxtCheckindate.setText(null);
         jtxtCheckoutdate.setText(null);
        jcomboRoomtype.setSelectedIndex(0);
         jcomboRoomno.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jtxtPostcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostcodeActionPerformed

    private void jtxtCustomerrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerrefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtntotal;
    private javax.swing.JComboBox<String> jcomboGender;
    private javax.swing.JComboBox<String> jcomboIdtype;
    private javax.swing.JComboBox<String> jcomboMeal;
    private javax.swing.JComboBox<String> jcomboRoomno;
    private javax.swing.JComboBox<String> jcomboRoomtype;
    private javax.swing.JTextField jtxtAddress1;
    private javax.swing.JTextField jtxtCheckindate;
    private javax.swing.JTextField jtxtCheckoutdate;
    private javax.swing.JTextField jtxtCustomerref;
    private javax.swing.JTextField jtxtDateofbirth;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtNationality;
    private javax.swing.JTextField jtxtPostcode;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTellno;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
